[initramfs] Reimplement aosupdate module using rsync approach
Signed-off-by: Oleksandr Grytsov <oleksandr_grytsov@epam.com>

diff --git a/recipes-core/initrdscripts/initramfs-framework/aosupdate b/recipes-core/initrdscripts/initramfs-framework/aosupdate
--- a/recipes-core/initrdscripts/initramfs-framework/aosupdate
+++ b/recipes-core/initrdscripts/initramfs-framework/aosupdate
@@ -1,65 +1,107 @@
 #!/bin/sh
 
+# This module requires the following boot parameters:
+#     aosupdate.device - specifies device where update artifacts are stored;
+#     aosupdate.path   - specifies path whre update artifacts are stored.
+
+# consts
+
 UPDATED_FLAG="updated"
 FAIL_FLAG="failed"
 DO_UPDATE_FLAG="do_update"
 DO_APPLY_FLAG="do_apply"
-UPDATE_DIR="/data/update/rootfs"
+
+UPDATE_MOUNT="/mnt/device"
+IMAGE_MOUNT="/mnt/image"
+
+UPDATE_IMAGE=""
+UPDATE_DIR="$UPDATE_MOUNT/${bootparam_aosupdate_path:-update_rootfs}"
 UPDATE_EXT="*.squashfs"
 
-[[ -z $ROOTFS_DIR ]] && ROOTFS_DIR="/rootfs"
+fail() {
+	local err="${1:-"unknown error"}"
 
-dmesg_msg() {
-	#NOTE <3> is KERN_ERR loglevel, which cause alerts to be sent
-	echo "<3>$1" >/dev/kmsg
+	# NOTE <3> is KERN_ERR loglevel, which cause alerts to be sent
+	echo "<3>Aos update failed: $err" >/dev/kmsg
+
+	# Put to fail flag file if update mounted
+	if grep -qs "$UPDATE_MOUNT" /proc/mounts; then
+		mkdir -p "$UPDATE_DIR"
+		echo "$err" >"$UPDATE_DIR/$FAIL_FLAG"
+	fi
+}
+
+error() {
+	(
+		echo "$@" 1>&2
+		exit 1
+	)
 }
 
 aosupdate_enabled() {
+	if [ -z ${bootparam_aosupdate_disk} ]; then
+		return 1
+	fi
+
+	if [ ! -e ${bootparam_aosupdate_disk} ]; then
+		msg "Aos update disabled: device ${bootparam_aosupdate_disk} not exist."
+		return 1
+	fi
+
 	return 0
 }
 
-do_switchroot() {
-	if grep -qs '/data' /proc/mounts && [ ! -f "$UPDATE_DIR/$UPDATED_FLAG" ]; then
-		umount /data
-	fi
+mount_update_disk() {
+	msg "Mount update disk: $bootparam_aosupdate_disk"
 
-	echo "Moving /dev, /proc and /sys onto rootfs..."
-
-	mount --move /dev $ROOTFS_DIR/dev
-	mount --move /proc $ROOTFS_DIR/proc
-	mount --move /sys $ROOTFS_DIR/sys
-
-	echo "Switching root to '$ROOTFS_DIR'..."
-
-	cd $ROOTFS_DIR
-	exec switch_root -c /dev/console $ROOTFS_DIR ${bootparam_init:-/sbin/init}
+	mkdir -p $UPDATE_MOUNT
+	mount $bootparam_aosupdate_disk $UPDATE_MOUNT
 }
 
-switch_if_fail() {
-	if [ $? -ne 0 ]; then
-		dmesg_msg "Initramfs: $1"
+umount_update_disk() {
+	if grep -qs "$UPDATE_MOUNT" /proc/mounts && [ ! -f "$UPDATE_DIR/$UPDATED_FLAG" ]; then
+		msg "Umount update disk: $bootparam_aosupdate_disk"
 
-		if grep -qs '/data' /proc/mounts; then
-			[[ -d $UPDATE_DIR ]] && touch $UPDATE_DIR/$FAIL_FLAG
-		fi
-
-		do_switchroot
+		umount $UPDATE_MOUNT
 	fi
 }
 
-mount_data() {
-	echo "Mount data $bootparam_userdata"
+mount_update_image() {
+	msg "Mount update image: $UPDATE_IMAGE"
 
-	mkdir -p /data
+	mkdir -p $IMAGE_MOUNT
+	mount $UPDATE_IMAGE $IMAGE_MOUNT
+}
 
-	mount -o defaults,usrjquota=aquota.user,jqfmt=vfsv0 $bootparam_userdata /data
-	switch_if_fail "can't mount /data"
+umount_update_image() {
+	if grep -qs "$IMAGE_MOUNT" /proc/mounts; then
+		msg "Umount update image: $UPDATE_IMAGE"
 
-	rm -rf $UPDATE_DIR/$FAIL_FLAG
+		umount $IMAGE_MOUNT
+	fi
+}
+
+# Possible actions are: update, apply, revert
+get_action() {
+	if [ -f "$UPDATE_DIR/$DO_APPLY_FLAG" ]; then
+		echo "apply"
+		return
+	fi
+
+	if [ -f "$UPDATE_DIR/$UPDATED_FLAG" ]; then
+		echo "revert"
+		return
+	fi
+
+	if [ -f "$UPDATE_DIR/$DO_UPDATE_FLAG" ]; then
+		echo "update"
+		return
+	fi
 }
 
 get_update_type() {
 	local update=$(cat $UPDATE_DIR/$DO_UPDATE_FLAG)
+
 	if [ -z $update ]; then
 		echo "full"
 	else
@@ -67,158 +109,122 @@ get_update_type() {
 	fi
 }
 
-# Possible actions are: full, incremental, apply, ignore
-get_action() {
-	[[ -f "$UPDATE_DIR/$DO_APPLY_FLAG" ]] && {
-		echo "apply"
-		return
-	}
+do_update() {
+	UPDATE_IMAGE="$(find "$UPDATE_DIR" -name "${UPDATE_EXT}" | head -n1)"
 
-	[[ -f "$UPDATE_DIR/$UPDATED_FLAG" ]] && {
-		echo "ignore"
-		return
-	}
+	local update_type="$(get_update_type)"
 
-	[[ -f "$UPDATE_DIR/$DO_UPDATE_FLAG" ]] && {
-		echo "$(get_update_type)"
-		return
-	}
+	msg "Start $update_type update..."
 
-	echo "ignore"
-}
-
-set_updated_part_flag() {
-	echo "Set updated partition flag $UPDATE_DIR/$UPDATED_FLAG"
-	touch $UPDATE_DIR/$UPDATED_FLAG
-}
-
-clear_update_part_flags() {
-	echo "Clear update partition flags $UPDATE_DIR/$UPDATED_FLAG $UPDATE_DIR/$DO_UPDATE_FLAG"
-	rm -f $UPDATE_DIR/$UPDATED_FLAG $UPDATE_DIR/$DO_UPDATE_FLAG
-}
-
-do_apply_update() {
-	update_type="$(get_update_type)"
-	update_file="$(find $UPDATE_DIR -name ${UPDATE_EXT} | head -n1)"
-
-	[ ! -z $update_file ]
-	switch_if_fail "update file not found"
-
-	echo "Got update file $update_file"
-
-	mkdir -p /update_layer
-	mount $update_file /update_layer
-	switch_if_fail "can't mount $update_file"
-
-	mount -o remount,rw $ROOTFS_DIR
-	switch_if_fail "can't remount rootfs"
-
-	if [ x$update_type == x"full" ]; then
-		echo "Apply full update"
-
-		mount -t selinuxfs selinuxfs /sys/fs/selinux
-		/sbin/semodule -i /usr/share/selinux/aos/base.pp
-
-		rm -rf $ROOTFS_DIR/*
-		cp -rafd --preserve=context /update_layer/* $ROOTFS_DIR
-		switch_if_fail "can't copy files"
-
-		echo "Full update applied"
-	else
-		echo "Apply incremental update"
-
-		cd /update_layer
-		find ./* -type c -exec rm -rf $ROOTFS_DIR/{} \;
-		find ./* -type d -exec mkdir -p {} $ROOTFS_DIR/{} \;
-		find ./* \( -type f -o -type l \) -exec cp -rafd {} $ROOTFS_DIR/{} \;
-		cd -
-
-		echo "Incremental update applied"
+	if [ -z "$UPDATE_IMAGE" ]; then
+		error "update iamge not found"
 	fi
 
-	rm -f $UPDATE_DIR/$DO_APPLY_FLAG
+	mount_update_image
 
-	umount /update_layer
-	umount /sys/fs/selinux
+	case "$update_type" in
+	full)
+		mount --move $IMAGE_MOUNT $ROOTFS_DIR
+		;;
+
+	incremental)
+		mount -t overlay overlay -o lowerdir=$IMAGE_MOUNT:$ROOTFS_DIR $ROOTFS_DIR
+		;;
+
+	*)
+		error "unknown update type: $update_type"
+		;;
+	esac
+
+	touch $UPDATE_DIR/$UPDATED_FLAG
+
+	msg "Successfully updated!"
+}
+
+do_revert() {
+	msg "Revert update"
+
+	clear_all_flags
+
+	error "update not confirmed"
+}
+
+cleanup() {
 	mount -o remount,ro $ROOTFS_DIR
+	umount_update_image
 }
 
-do_mount_full_update() {
-	update_file="$(find $UPDATE_DIR -name ${UPDATE_EXT} | head -n1)"
-
-	[ ! -z $update_file ]
-	switch_if_fail "update file not found"
-
-	echo "Mount full update image $update_file"
-
-	mkdir -p /update_layer
-
-	mount $update_file /update_layer
-	switch_if_fail "can't mount full image"
-
-	mount --move /update_layer $ROOTFS_DIR
-	switch_if_fail "can't move full image"
+clear_all_flags() {
+	rm -f "$UPDATE_DIR/$DO_UPDATE_FLAG" "$UPDATE_DIR/$UPDATED_FLAG" "$UPDATE_DIR/$DO_APPLY_FLAG" "$UPDATE_DIR/$FAIL_FLAG"
 }
 
-do_mount_inc_update() {
-	update_file=$(find $UPDATE_DIR -name ${UPDATE_EXT} | head -n1)
+do_apply() {
+	UPDATE_IMAGE="$(find "$UPDATE_DIR" -name "${UPDATE_EXT}" | head -n1)"
 
-	echo "Mount incremental update image $update_file"
+	local update_type="$(get_update_type)"
 
-	mkdir -p /update_layer
+	msg "Start $update_type apply..."
 
-	mount $update_file /update_layer
-	switch_if_fail "can't mount incremental image"
+	mount_update_image
+	mount -o remount,rw $ROOTFS_DIR
 
-	mount -t overlay overlay -o lowerdir=/update_layer:$ROOTFS_DIR $ROOTFS_DIR
-	switch_if_fail "can't mount incremental image"
+	case "$update_type" in
+	full)
+		rsync -av -A -X --ignore-times --delete $IMAGE_MOUNT/ $ROOTFS_DIR/
+		;;
+
+	incremental)
+		rsync -av -A -X --ignore-times $IMAGE_MOUNT/ $ROOTFS_DIR/
+
+		find $ROOTFS_DIR/ -type c -exec rm -f {} \;
+		;;
+	*)
+		error "unknown update type: $update_type"
+		;;
+	esac
+
+	cleanup
+	clear_all_flags
+
+	msg "Successfully applied!"
 }
 
 aosupdate_run() {
-	if [ -n "$ROOTFS_DIR" ]; then
-		if [ ! -d $ROOTFS_DIR/dev ]; then
-			fatal "There's no '/dev' on rootfs."
-		fi
+	msg "======================================= Aos update ======================================="
 
-		[[ -z $bootparam_userdata ]] && {
-			echo "Userdata partition is not set, skipping initramfs"
-			do_switchroot
-		}
+	err=$(
+		{
+			set -e
 
-		mount_data
+			mount_update_disk
 
-		action="$(get_action)"
+			case "$(get_action)" in
+			update)
+				do_update
+				;;
 
-		case "$action" in
-		full)
-			echo "Action: full"
+			revert)
+				do_revert
+				;;
 
-			do_mount_full_update
-			set_updated_part_flag
-			;;
-		incremental)
-			echo "Action: incremental"
+			apply)
+				do_apply
+				;;
 
-			do_mount_inc_update
-			set_updated_part_flag
-			;;
-		apply)
-			echo "Action: apply"
+			*)
+				msg "Aos update: no action selected"
+				;;
+			esac
 
-			do_apply_update
-			;;
-		ignore)
-			echo "Action: ignoring update"
+		} 2>&1 >/dev/null
+	)
 
-			clear_update_part_flags
-			;;
-		*)
-			echo "Fail: Unexpected action received- $action"
-			;;
-		esac
-
-		do_switchroot
-	else
-		debug "No rootfs has been set"
+	if [ $? -ne 0 ]; then
+		fail "$err"
+		cleanup
 	fi
+
+	umount_update_disk
+
+	msg "=========================================================================================="
 }
